apiVersion: v1
kind: Service
metadata:
  name: cs-appstore
  labels:
    app: cs-appstore
spec:
  type: NodePort 
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 30002
  selector:
    app: cs-appstore
