# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivot_hail', '0002_auto_20190213_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hailstatus',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hailstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='HailStatus',
        ),
    ]
