kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-volume
  labels:
    app: cs-appstore
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
